### ISSUE TITLE
docker: setfacl step fails when using user-provided certificates

### ISSUE THREAD

**Issue by aellwein** [albertito/chasquid#29]
I want to use chasquid in my cloud environment (k8s) and had a look at the bundled Dockerfile, however, there is an issue: 
in [entrypoint.sh](https://github.com/albertito/chasquid/blob/5c51f749417c8b73f77221e418b77b0027146a86/docker/entrypoint.sh#L71) there is an assumption, that certificates are located _inside_ the Docker container, or created on its filesystem.

However, it's not applicable in my use case: i want the certificates to be managed/renewed by [cert-manager](https://github.com/cert-manager/cert-manager) and i want just mount them into chasquid's container, but in this case the ``setfacl`` logic is not working.

@albertito Can you suggest here something? Should i use my own version of Dockerfile / entrypoint.sh?

**Comment by albertito** [comment]
Thanks for reporting this!

That's definitely a use case the default Dockerfile should support, so it's a bug.

There's already a bit of logic for this above, based on the `$AUTO_CERTS` variable. Maybe we should only do `setfacl` if we've done `certbot renew`.

The other concern I have are permissions for your externally-provided certificates, but I think at that point since they're external you can probably manage that without needing to adjust the Dockerfile?

What do you think?

**Comment by aellwein** [comment]
> The other concern I have are permissions for your externally-provided certificates, but I think at that point since they're external you can probably manage that without needing to adjust the Dockerfile?
> 
> What do you think?
Sounds good to me. I can adjust file mode of the files mounted to the pod. The only thing i probably need to take care of is an unattended restart of chasquid upon certificate renewal. I think i can manage this by means of writing a small k8s operator which needs to watch on certificate resources. I already did something like this
in my [cert-backup-operator](https://github.com/aellwein/cert-backup-operator), should be no big deal here.

**Comment by albertito** [comment]
Great! I've submitted 567ad3512201958880bbe505ec23bce1f785d39d to `next` moving the setfacl inside the conditional that renews the certificate.

Docker images are [automatically built by the CI pipeline](https://gitlab.com/albertito/chasquid/-/pipelines/621045060) and uploaded to the gitlab registry and dockerhub, so you should be able to give them a try by using the `next` image tag.

Please let me know how it goes! Thank you!

**Comment by albertito** [comment]
The fix was included in [chasquid 1.10 (2022-09-02)](https://blitiri.com.ar/p/chasquid/relnotes/#110-2022-09-01).

**Comment by Guiorgy** [comment]
I user Nginx as a web proxy, so the ports `80` and `443` are not available, as such, the certbot inside this container can not work, at least not with the standard challenge where a file needs to be accessed over http (even for Nginx I use DNS challenge instead anyway). So instead, I can have chasquid use the certificates generated by the certbot inside the Nginx container, and incase anybody else needs this, here's how I did it by overriding the entrypoint:

```yaml
services:
  chasquid:
    ports:
      # chasquid: SMTP, submission, submission+tls.
      - 25:25/tcp
      - 465:465/tcp
      - 587:587/tcp
      # dovecot: POP3s, IMAPs, managesieve.
      - 993:993/tcp
      - 995:995/tcp
      - 4190:4190/tcp
      # http for letsencrypt/certbot.
      #- 80:80/tcp
      #- 443:443/tcp
    environment:
      #AUTO_CERTS: example.com
      TZ: Asia/Tbilisi
    volumes:
      - data:/data
      - nginx_proxy_manager_letsencrypt:/etc/npm-letsencrypt:ro
    entrypoint: >
      /bin/sh -c '
        if ! [ -d /etc/letsencrypt/live/npm-19 ]; then
          mkdir -p /etc/letsencrypt/live/npm-19 &&
          chown chasquid:chasquid /etc/letsencrypt/live &&
          chown chasquid:chasquid /etc/letsencrypt/live/npm-19;
        fi &&
        if [ -f /etc/letsencrypt/live/npm-19/cert.pem ]; then
          rm /etc/letsencrypt/live/npm-19/cert.pem /etc/letsencrypt/live/npm-19/chain.pem /etc/letsencrypt/live/npm-19/fullchain.pem /etc/letsencrypt/live/npm-19/privkey.pem;
        fi &&
        cp $(readlink -f /etc/npm-letsencrypt/live/npm-19/cert.pem) /etc/letsencrypt/live/npm-19/cert.pem && chown chasquid:chasquid /etc/letsencrypt/live/npm-19/cert.pem &&
        cp $(readlink -f /etc/npm-letsencrypt/live/npm-19/chain.pem) /etc/letsencrypt/live/npm-19/chain.pem && chown chasquid:chasquid /etc/letsencrypt/live/npm-19/chain.pem &&
        cp $(readlink -f /etc/npm-letsencrypt/live/npm-19/fullchain.pem) /etc/letsencrypt/live/npm-19/fullchain.pem && chown chasquid:chasquid /etc/letsencrypt/live/npm-19/fullchain.pem &&
        cp $(readlink -f /etc/npm-letsencrypt/live/npm-19/privkey.pem) /etc/letsencrypt/live/npm-19/privkey.pem && chown chasquid:chasquid /etc/letsencrypt/live/npm-19/privkey.pem &&
        exec /entrypoint.sh
      '

networks:
  bridge:
    external: false

volumes:
  data:
    external: false
  nginx_proxy_manager_letsencrypt:
    external: true
```
